name: Daily AI News Report

# 언제 실행할지 정하는 부분
on:
  schedule:
    - cron: '0 0 * * *' # 매일 한국 시간 오전 9시에 자동 실행 (UTC 기준 0시)
  workflow_dispatch: # 수동으로 버튼을 눌러서 실행


jobs:
  run-ai-pipeline:
    runs-on: ubuntu-latest 
    
    steps:
      - name: 내 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설치하기
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 라이브러리(장바구니) 설치하기
        run: pip install -r requirements.txt

      - name: 파이썬 코드 실행하기!
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
